version: '3.8'

services:
  graphhopper:
    image: israelhikingmap/graphhopper
    container_name: graphhopper
    ports:
      - "8989:8989"
    volumes:
      - ../graphhopper-data:/data
    entrypoint: java
    command:
      - -Xmx2g
      - -Xms2g
      - "-Ddw.graphhopper.datareader.file=/data/turkey-latest.osm.pbf"
      - "-Ddw.graphhopper.graph.location=/data/graph-cache"
      - "-Ddw.graphhopper.ch.enabled=false"
      - -jar
      - graphhopper-web-11.0-SNAPSHOT.jar
      - server
      - config-example.yml
